/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FactoryRouteImport } from './routes/factory'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopIdRouteImport } from './routes/shop.$id'
import { Route as VaultIndexRouteImport } from './routes/vault.index'
import { Route as VaultIdRouteImport } from './routes/vault.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FactoryRoute = FactoryRouteImport.update({
  id: '/factory',
  path: '/factory',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopIdRoute = ShopIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShopRoute,
} as any)
const VaultIndexRoute = VaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VaultRoute,
} as any)
const VaultIdRoute = VaultIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VaultRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/factory': typeof FactoryRoute
  '/ledger': typeof LedgerRoute
  '/playbook': typeof PlaybookRoute
  '/shop': typeof ShopRouteWithChildren
  '/vault': typeof VaultRouteWithChildren
  '/shop/$id': typeof ShopIdRoute
  '/vault/$id': typeof VaultIdRoute
  '/shop/': typeof ShopIndexRoute
  '/vault/': typeof VaultIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/factory': typeof FactoryRoute
  '/ledger': typeof LedgerRoute
  '/playbook': typeof PlaybookRoute
  '/shop/$id': typeof ShopIdRoute
  '/vault/$id': typeof VaultIdRoute
  '/shop': typeof ShopIndexRoute
  '/vault': typeof VaultIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/factory': typeof FactoryRoute
  '/ledger': typeof LedgerRoute
  '/playbook': typeof PlaybookRoute
  '/shop': typeof ShopRouteWithChildren
  '/vault': typeof VaultRouteWithChildren
  '/shop/$id': typeof ShopIdRoute
  '/vault/$id': typeof VaultIdRoute
  '/shop/': typeof ShopIndexRoute
  '/vault/': typeof VaultIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/factory'
    | '/ledger'
    | '/playbook'
    | '/shop'
    | '/vault'
    | '/shop/$id'
    | '/vault/$id'
    | '/shop/'
    | '/vault/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/factory'
    | '/ledger'
    | '/playbook'
    | '/shop/$id'
    | '/vault/$id'
    | '/shop'
    | '/vault'
  id:
    | '__root__'
    | '/'
    | '/factory'
    | '/ledger'
    | '/playbook'
    | '/shop'
    | '/vault'
    | '/shop/$id'
    | '/vault/$id'
    | '/shop/'
    | '/vault/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FactoryRoute: typeof FactoryRoute
  LedgerRoute: typeof LedgerRoute
  PlaybookRoute: typeof PlaybookRoute
  ShopRoute: typeof ShopRouteWithChildren
  VaultRoute: typeof VaultRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factory': {
      id: '/factory'
      path: '/factory'
      fullPath: '/factory'
      preLoaderRoute: typeof FactoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$id': {
      id: '/shop/$id'
      path: '/$id'
      fullPath: '/shop/$id'
      preLoaderRoute: typeof ShopIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/vault/': {
      id: '/vault/'
      path: '/'
      fullPath: '/vault/'
      preLoaderRoute: typeof VaultIndexRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/$id': {
      id: '/vault/$id'
      path: '/$id'
      fullPath: '/vault/$id'
      preLoaderRoute: typeof VaultIdRouteImport
      parentRoute: typeof VaultRoute
    }
  }
}

interface ShopRouteChildren {
  ShopIdRoute: typeof ShopIdRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopIdRoute: ShopIdRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface VaultRouteChildren {
  VaultIdRoute: typeof VaultIdRoute
  VaultIndexRoute: typeof VaultIndexRoute
}

const VaultRouteChildren: VaultRouteChildren = {
  VaultIdRoute: VaultIdRoute,
  VaultIndexRoute: VaultIndexRoute,
}

const VaultRouteWithChildren = VaultRoute._addFileChildren(VaultRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FactoryRoute: FactoryRoute,
  LedgerRoute: LedgerRoute,
  PlaybookRoute: PlaybookRoute,
  ShopRoute: ShopRouteWithChildren,
  VaultRoute: VaultRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
